name: snakegame
description: "Fidi - Snake Game - A cross-platform classic snake game built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.7

msix_config:
  display_name: Fidi - Snake Game
  publisher_display_name: ZarabandaJose
  identity_name: ZarabandaJose.Fidi-SnakeGame
  publisher: CN=73F75044-1C00-4198-B32A-7DC00F5DAE1A
  msix_version: 1.0.0.0
  logo_path: assets/icon.png
  store: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon.png
